{
 "title": "Readout DB",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Run State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "Run Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "Files Written",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "RW Buffer Overflow Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "Error BitWord",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "Last Command",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "Trigger Rate [Hz]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "DMA Rate [Hz]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "Avg. Event Size [kB]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "DMA Loops",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "Data Received [GB]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "Trigger & DMA Rates [Hz]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json, CONVERT_TZ(ts, 'America/New_York', '+00:00') AS time FROM pgrams_metrics.tpc_metrics\n"
    }
   ]
  },
  {
   "title": "Avg. Event Size [kB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json, CONVERT_TZ(ts, 'America/New_York', '+00:00') AS time FROM pgrams_metrics.tpc_metrics"
    }
   ]
  },
  {
   "title": "Active DAQs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.orch_metrics"
    }
   ]
  },
  {
   "title": "Error BitWord",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.orch_metrics"
    }
   ]
  },
  {
   "title": "Last Command",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json FROM pgrams_metrics.orch_metrics"
    }
   ]
  },
  {
   "title": "CPU & Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json, CONVERT_TZ(ts, 'America/New_York', '+00:00') AS time FROM pgrams_metrics.orch_metrics "
    }
   ]
  },
  {
   "title": "Free Disk Space [GB]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json, CONVERT_TZ(ts, 'America/New_York', '+00:00') AS time FROM pgrams_metrics.orch_metrics"
    }
   ]
  },
  {
   "title": "CPU Temperature [C]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "pgrams_metrics",
     "rawSql": "SELECT data_json, CONVERT_TZ(ts, 'America/New_York', '+00:00') AS time FROM pgrams_metrics.orch_metrics "
    }
   ]
  },
  {
   "title": "Charge Channel Baseline",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 56 },
   "targets": [
    { "topic": "metrics/tpc_monitor" }
   ]
  },
  {
   "title": "Charge Channel Avg Num Hits",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 67 },
   "targets": [
    { "topic": "metrics/tpc_monitor" }
   ]
  },
  {
   "title": "Light Channel Baseline",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 78 },
   "targets": [
    { "topic": "metrics/tpc_monitor" }
   ]
  },
  {
   "title": "Light Avg ROIs / Event",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 89 },
   "targets": [
    { "topic": "metrics/tpc_monitor" }
   ]
  }
 ]
}